# https://docs.docker.com/compose/rails/
# docker-compose run --no-deps web rails new . --force --database=postgresql
# docker-compose build
# docker-compose up
# docker-compose run web rake db:create
# docker-compose down
# docker-compose up

# After any codebase change:
# - docker-compose build
# - docker-compose up

version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3005:3000"
    depends_on:
      - db